### ISSUE TITLE
Android v2 embedding support

### ISSUE THREAD

**Issue by vanlooverenkoen** [luis901101/blue_bird_scanner#1]
```
The plugins `blue_bird_scanner` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

```

**Comment by luis901101** [comment]
Make sure you are using the latest version `blue_bird_scanner: ^2.0.1+5`. This version is updated since 2021-09-13 to support Android Embedding v2, check [Changelog here](https://pub.dev/packages/blue_bird_scanner/changelog).
Check if your `pubspec.lock` is using latest version. Any way you can `flutter pub upgrade` to ensure all dependencies to upgrade to latest available/possible.
